name: KnockDC
description: 'The KnockIT Discord Integration Plugin'
version: '1.0.0'
main: io.github.keishispl.knockDC.KnockDC
api-version: '1.21'
authors: [ keishispl ]
load: STARTUP
commands:
    knockdc:
        description: 'The main command for KnockDC'
        permission: 'knockdc.command'
        permission-message: 'You do not have permission to use this command'